# Generated by Django 5.1.6 on 2025-05-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_task_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
    ]
